# Generated by Django 5.2.4 on 2025-09-24 04:36

import resumes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='resume',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='portfolio',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=resumes.models.profile_image_upload_path),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.TextField(help_text='Format: Degree | Institution | Dates | Details'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(help_text='Format: Job Title | Company | Dates | Description'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=resumes.models.resume_upload_path),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(help_text='Enter skills separated by commas or new lines'),
        ),
    ]
