# Generated by Django 5.2.4 on 2025-09-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resume_address_resume_linkedin_resume_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
