# Generated by Django 5.2.4 on 2025-09-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resume_download_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='expertise',
            field=models.TextField(blank=True, help_text='Enter your areas of expertise separated by commas or new lines'),
        ),
        migrations.AddField(
            model_name='resume',
            name='languages',
            field=models.TextField(blank=True, help_text='Format: Language | Proficiency Level (e.g., English | Fluent)'),
        ),
        migrations.AddField(
            model_name='resume',
            name='references',
            field=models.TextField(blank=True, help_text='Format: Name | Profession | Phone | Email (one per line)'),
        ),
    ]
